spring:
  application:
    name: remindme

  datasource:
    url: jdbc:postgresql://ep-snowy-smoke-acaf576c-pooler.sa-east-1.aws.neon.tech/remindme?sslmode=require
    username: remember_me_owner
    password: npg_9bWmMAXw7TDi
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000

frontend:
  url: http://localhost:3000